---
name: Build Java PR

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@badc26f9f0990b88efe47a8da457b23267d674d2 # 1.22.55
    secrets: inherit
